# utils/emojis.py

E = {
    "loading":      "",
    "star":         "",
    "rules":        "",
    "pin":          "",
    "question":     "",
    "dash":         "",
    "exclaim":      "",
    "arrow_white":  "",
    "fire_white":   "",
    "verified":     "",
    "fire_blue":    "",
    "muted":        "",
    "deafened":     "",
    "arrow_blue":   "",
    "n1":           "",
    "n2":           "",
    "n3":           "",
    "n4":           "",
    "n5":           "",
    "n6":           "",
    "n7":           "",
    "circle":       "",
    "mail":         "",
    "trophy":       "",
    "bulb":         "",
    "warning":      "",
    "extra1":       "",
    "extra2":       "",
    "extra3":       "",
    "extra4":       "",
    "extra5":       "",
    "extra6":       "",
    "extra7":       "",
}
